services:
  open-xliff-translator:
    build: .
    container_name: open-xliff-translator
    restart: unless-stopped
    ports:
      - "5003:5003"  # ✅ Corrected port mapping
    volumes:
      - openxliff_uploads:/app/uploads
      - openxliff_processed:/app/processed
    environment:
      - FLASK_DEBUG=True
    depends_on:
      - libretranslate

  libretranslate:
    image: libretranslate/libretranslate
    container_name: open-xliff-libretranslate
    restart: unless-stopped
    ports:
      - "5002:5000"
    environment:
      - LT_LOAD_ONLY=en,da

volumes:
  openxliff_uploads:
  openxliff_processed:
