services:
  backend:
    build: ./backend
    ports:
      - "5002:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    depends_on:
      - libretranslate

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=en,da
    restart: always
